### ISSUE TITLE
DISPLAY 4 DIGITS: No decimal needed BTC

### ISSUE THREAD

**Issue by vdisclafani** [RockyTV/yabpt#34]
Love this extension because very few tickers display a Crypto value without clicking on the icon !  
You have improved on Alexandre Oliveira's ticker, which only displayed 2 digits (far too little precision to be useful).
HOWEVER,why not stop displaying the decimal and use all four 'places' to display numerical values, 
with the understanding (of the user) that they must use another extension that, for example, has a popup or dropdown box for absolute confirmation that BTC has not dropped in price to 4 digits USD of value, or risen to 6 digits USD (left of decimal).  
(Perhaps you wish to add a popup or dropdown box to display the true (complete) BTC value to your extension -- that would be awesome!)
Anyone with any knowledge whatsoever of the Bitcoin market (ie. anyone who would be interested in an extension constantly displaying a BTC in their browser toolbar) would accurately assume that a BTC icon displaying '1175' for BTC almost certainly means $ 11,750  NOT $1,750  (unless the Apocalypse has come, or we have been invaded by Aliens from Planet 9, at which point Plan B for Earthlings is definitely of more interest than the current BTC price, ha!).
On a serious note, for an BTC investor (or anyone who holds BTC) , there is a lot of difference between a BTC icon display price of 1170 ($11,700.) ranging to 1179 ($11,790.) insofar as the displayed value necessitates an action to buy or sell BTC.   Knowing whether to buy or sell BTC 'at a glance' (from the 4 place numerical BTC icon value) would truly increase the value of the extension for me, and I think for any user of your extension.
Thank you for listening, and for your selflessness in programming for the public -- I admire you!  
Victoria
(Victoria Di Sclafani, MPH, PhD -- retired; neuroscience research Yale Med School)
P.S.  Should you decide to accept this mission, ha!, I will surely be pushing a little BTC your way...

**Comment by Xinayder** [comment]
First of all:

> You have improved on Alexandre Oliveira's ticker, which only displayed 2 digits (far too little precision to be useful).

In case you haven't noticed me and him are the same person.

> HOWEVER,why not stop displaying the decimal and use all four 'places' to display numerical values,

The extension already does this. https://github.com/RockyTV/yabpt/blob/ffc3463829dce45f3d10d70f67ddb167d0dbafd7/src/background.js#L9

This function parses the price obtained via Blockchain.info API into a readable string that indicates the order of magnitude of the price of the selected currency. In other words, it displays 66K, for example, if the price is between 65,600 and 66,000.

The problem with these button badges is that they only support 4 characters, which is a problem I faced before, and it was worse because some text would get cut in Linux (it's still being cut), so I decided to go with this approach as it was easier and I figured it would be much more indicative than having a number in the wrong magnitude being displayed.

And lastly,

> On a serious note, for an BTC investor (or anyone who holds BTC) , there is a lot of difference between a BTC icon display price of 1170 ($11,700.) ranging to 1179 ($11,790.) insofar as the displayed value necessitates an action to buy or sell BTC. Knowing whether to buy or sell BTC 'at a glance' (from the 4 place numerical BTC icon value)

If you're taking decisions based on an extension that provides a short "preview" of the current BTC value and from a single source, maybe you're doing it wrong; if you were a real investor you wouldn't be using an extension like this to base your buy/sell orders, you'd be watching a much more detailed graph to take your decisions instead of this extension.

**Comment by vdisclafani** [comment]
A programmer with aliases, huh? Thanks for explanation, and thank you for your skills!

Victoria
Dr. Di Sclafani
Sent with [ProtonMail](https://protonmail.com/?utm_campaign=ww-all-2a-mail-pmm_mail-protonmail_signature&utm_source=proton_users&utm_medium=cta&utm_content=sent_with_protonmail_secure_email) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
